# File used by GitHub Actions

name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test on ${{ matrix.cfg.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
        cfg:
          - os: ubuntu-latest

    steps:
      - name: Set up git repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          # More info on options: https://github.com/conda-incubator/setup-miniconda
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          channels: defaults
          activate-environment: numerical-methods
          auto-update-conda: true
          auto-activate-base: false
          show-channel-urls: true

      - name: Run the project
        shell: bash -l {0}
        run: python3 main.py
